// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Hadekha Erfadila Fitra",
            "email": "hdkef11@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/articles": {
            "get": {
                "description": "get all articles navigated by last-id and limit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "get all articles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the last article in recent array of article",
                        "name": "last-id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "how many article you want to take",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagmodel.GetArticle"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create an article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "create an article",
                "parameters": [
                    {
                        "description": "create an article",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputArticle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/articles/{id}": {
            "get": {
                "description": "get detail of article specified by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "get one article",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of article",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.GetArticle"
                        }
                    }
                }
            },
            "put": {
                "description": "update an article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "update an article",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of article",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update an article",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputArticle"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete an article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "articles"
                ],
                "summary": "delete an article",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of article",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/comments/{article-id}": {
            "get": {
                "description": "get all comments navigated by last-id and limit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "get all comments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of article",
                        "name": "article-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the last comment in recent array of comment",
                        "name": "last-id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "how many comment you want to take",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagmodel.GetComment"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create an comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "create an comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of article",
                        "name": "article-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "create an comment",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputComment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/comments/{id}": {
            "put": {
                "description": "update an comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "update an comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of comment",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update an comment",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputComment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete an comment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "delete an comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of comment",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/drafts": {
            "get": {
                "description": "get all drafts navigated by last-id and limit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "get all drafts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the last draft in recent array of draft",
                        "name": "last-id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "how many draft you want to take",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagmodel.GetDraft"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create an draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "create an draft",
                "parameters": [
                    {
                        "description": "create an draft",
                        "name": "draft",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputDraft"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/drafts/{id}": {
            "get": {
                "description": "get detail of draft specified by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "get one draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of draft",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.GetDraft"
                        }
                    }
                }
            },
            "put": {
                "description": "update an draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "update an draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of draft",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update an draft",
                        "name": "draft",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputDraft"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete an draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "delete an draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of draft",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "get all users navigated by last-id and limit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get all users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the last user in recent array of user",
                        "name": "last-id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "how many user you want to take",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagmodel.GetUser"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "create an user",
                "parameters": [
                    {
                        "description": "create an user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "get detail of user specified by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get one user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.GetUser"
                        }
                    }
                }
            },
            "put": {
                "description": "update an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "update an user, only super-admin can update role",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update an user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagmodel.InputUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete an user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "delete an user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}/public": {
            "get": {
                "description": "get detail of user specified by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get one user public information (without password information)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagmodel.GetUserPublic"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swagmodel.GetArticle": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "creatorID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imageURL": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "swagmodel.GetComment": {
            "type": "object",
            "properties": {
                "articleID": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "creatorID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "swagmodel.GetDraft": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "creatorID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imageURL": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "swagmodel.GetUser": {
            "type": "object",
            "properties": {
                "avatarURL": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "swagmodel.GetUserPublic": {
            "type": "object",
            "properties": {
                "avatarURL": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "swagmodel.InputArticle": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "imageURL": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "swagmodel.InputComment": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                }
            }
        },
        "swagmodel.InputDraft": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "creatorID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imageURL": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "swagmodel.InputUser": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "swagmodel.Response": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "OAuth2AccessCode": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information"
            }
        },
        "OAuth2Application": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Implicit": {
            "type": "oauth2",
            "flow": "implicit",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "read": " Grants read access",
                "write": " Grants write access"
            }
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Bloggo API",
	Description: "This is a headless content management system",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
